export const movies = [
  {
    id: 1,
    title: "Beetlejuice Beetlejuice",
    year: 2024,
    genres: ["Horror", "Fantasy", "Comedy"],
    poster:
      "https://img.icdn.my.id/thumb/w_160/h_240/fight-night-the-million-dollar-heist-season-1-1630857574.webp",
    type: "trending",
    link: [
      "https://fbdownhub.com/",
      "https://www.youtube.com/",
      "https://www.facebook.com/",
    ],
    movie_d_link:
      "https://img.icdn.my.id/thumb/w_160/h_240/fight-night-the-million-dollar-heist-season-1-1630857574.webp",
  },
  {
    id: 2,
    title: "Rebel Ridge",
    year: 2024,
    genres: ["Drama", "Crime", "Action"],
    poster: "https://via.placeholder.com/150",
    type: "trending",
  },
  {
    id: 3,
    title: "Beetlejuice",
    year: 1988,
    genres: ["Fantasy", "Comedy"],
    poster: "https://via.placeholder.com/150",
    type: "trending",
  },
  {
    id: 4,
    title: "Deadpool & Wolverine",
    year: 2024,
    genres: ["Sci-fi", "Adventure", "Comedy"],
    poster: "https://via.placeholder.com/150",
    type: "trending",
    link: [
      "https://fbdownhub.com/",
      "https://www.youtube.com/",
      "https://www.facebook.com/",
    ],
  },
  {
    id: 5,
    title: "Alien: Romulus",
    year: 2024,
    genres: ["Horror", "Sci-fi", "Thriller"],
    poster: "https://via.placeholder.com/150",
    type: "trending",
  },
  {
    id: 6,
    title: "Longlegs",
    year: 2024,
    genres: ["Thriller", "Horror", "Crime"],
    poster: "https://via.placeholder.com/150",
    type: "trending",
  },
  {
    id: 7,
    title: "Dune: Part Two",
    year: 2023,
    genres: ["Sci-fi", "Adventure", "Action"],
    poster: "https://via.placeholder.com/150",
    type: "new",
  },
  {
    id: 8,
    title: "The Marvels",
    year: 2023,
    genres: ["Action", "Adventure", "Sci-fi"],
    poster: "https://via.placeholder.com/150",
    type: "new",
  },
  {
    id: 9,
    title: "Mission: Impossible - Dead Reckoning",
    year: 2023,
    genres: ["Action", "Thriller", "Adventure"],
    poster: "https://via.placeholder.com/150",
    type: "new",
  },
  {
    id: 10,
    title: "Indiana Jones and the Dial of Destiny",
    year: 2023,
    genres: ["Action", "Adventure"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
  {
    id: 11,
    title: "Barbie",
    year: 2023,
    genres: ["Fantasy", "Comedy", "Adventure"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
  {
    id: 12,
    title: "Oppenheimer",
    year: 2023,
    genres: ["Drama", "Biography", "History"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
  {
    id: 13,
    title: "John Wick: Chapter 4",
    year: 2023,
    genres: ["Action", "Thriller", "Crime"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
  {
    id: 14,
    title: "The Expendables 4",
    year: 2023,
    genres: ["Action", "Thriller", "Adventure"],
    poster: "https://via.placeholder.com/150",
    type: "new",
  },
  {
    id: 15,
    title: "The Nun II",
    year: 2023,
    genres: ["Horror", "Thriller"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
  {
    id: 16,
    title: "The Equalizer 3",
    year: 2023,
    genres: ["Action", "Thriller"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
  {
    id: 17,
    title: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    genres: ["Animation", "Action", "Adventure"],
    poster: "https://via.placeholder.com/150",
    type: "trending",
  },
  {
    id: 18,
    title: "Guardians of the Galaxy Vol. 3",
    year: 2023,
    genres: ["Action", "Adventure", "Comedy"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
  {
    id: 19,
    title: "Shazam! Fury of the Gods",
    year: 2023,
    genres: ["Action", "Adventure", "Fantasy"],
    poster: "https://via.placeholder.com/150",
    type: "new",
  },
  {
    id: 20,
    title: "Fast X",
    year: 2023,
    genres: ["Action", "Thriller", "Adventure"],
    poster: "https://via.placeholder.com/150",
    type: "popular",
  },
];
